### ISSUE TITLE
chat.postMessage timeouts not configurable?

### ISSUE THREAD

**Issue by pumpadump** [flyberry-capital/scala-slack#4]
thanks for the great scala/slack api.
Is it possible to configure the timout values for the chat.postMessage method somehow?
It times out nearly 50% of the times for us. 

java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1147)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at scalaj.http.Http$$anonfun$9.apply(Http.scala:434)
    at scalaj.http.Http$$anonfun$9.apply(Http.scala:432)
    at scalaj.http.Http$Request.process(Http.scala:159)
    at scalaj.http.Http$Request.apply(Http.scala:141)
    at scalaj.http.Http$Request.asString(Http.scala:207)
    at com.flyberrycapital.slack.HttpClient.post(HttpClient.scala:81)
    at com.flyberrycapital.slack.Methods.Chat.postMessage(Chat.scala:80)
    at actors.NotificationActor.notifySlack(NotificationActor.scala:73)
    at actors.NotificationActor$$anonfun$receive$1.applyOrElse(NotificationActor.scala:59)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at actors.NotificationActor.aroundReceive(NotificationActor.scala:22)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
    at akka.dispatch.Mailbox.run(Mailbox.scala:221)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ksolan** [comment]
You can configure both read and conn timeouts for the entire Slack client:

```scala
val s = new SlackClient(<API_TOKEN>)
s.connTimeout(1000) # 1000 ms
s.readTimeout(5000) # 5000 ms
```
Hopefully setting it to a higher value fixes the problem!

**Comment by pumpadump** [comment]
Ah ok sry, I didn't realize that version 0.2.0 is out. I was using version 0.1.1 which didn't contain these methods.
